/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface NexoraEscrowInterface extends Interface {
    getFunction(nameOrSignature: "amount" | "buyer" | "getBalance" | "refundBuyer" | "releaseFunds" | "seller" | "status"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'amount', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyer', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'refundBuyer', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseFunds', values?: undefined): string;
encodeFunctionData(functionFragment: 'seller', values?: undefined): string;
encodeFunctionData(functionFragment: 'status', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'amount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundBuyer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'status', data: BytesLike): Result;
  }

  

  export interface NexoraEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): NexoraEscrow;
    waitForDeployment(): Promise<this>;

    interface: NexoraEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    amount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buyer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    refundBuyer: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    releaseFunds: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    seller: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    status: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'amount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'refundBuyer'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseFunds'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'seller'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'status'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }